apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  PARAM: mssql
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
type: Opaque
data:
  CONNECTION_STR: RGF0YSBTb3VyY2U9bXlhcHAtbXNzcWwtbGludXg7SW5pdGlhbCBDYXRhbG9nPU90dXNMYWI7SW50ZWdyYXRlZCBTZWN1cml0eT1GYWxzZTtVc2VyIElEPXNhO1Bhc3N3b3JkPVBzZDEyMzQlCg==
  SA_PASSWORD: UHNkMTIzNCU=